global:
  scrape_interval: 5s # 默认抓取间隔

  external_labels:
    monitor: 'NATS Server'
scrape_configs:
  - job_name: 'nats_exporter'
    static_configs:
      - targets: ['host.docker.internal:7777'] 
