---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-0
spec:
  capacity:
    storage: 1.5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs-for-test/performance/kv_benchmark
    server: 172.16.168.2
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
spec:
  capacity:
    storage: 1.5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs-for-test/performance/kv_benchmark
    server: 172.16.168.2
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-2
spec:
  capacity:
    storage: 1.5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs-for-test/performance/kv_benchmark
    server:  172.16.168.2
  storageClassName: nfs-storage

