---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-0
spec:
  capacity:
    storage: 1.5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/raid0/nfs
    server: 192.168.14.38
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
spec:
  capacity:
    storage: 1.5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/raid0/nfs
    server: 192.168.14.38
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-2
spec:
  capacity:
    storage: 1.5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/raid0/nfs
    server: 192.168.14.38
  storageClassName: nfs-storage

