apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-config
  namespace: ns-benchmark
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  local:
    path: /home/selab/Desktop/kv_benchmark/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - selab-asus-expertcenter-d900mdr-m900mdr
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-config
  namespace: ns-benchmark
spec:
  volumeName: local-pv-config
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 1Gi
  storageClassName: standard
