apiVersion: v1
kind: Service
metadata:
  name: nats-external-service
  namespace: ns-benchmark
spec:
  type: NodePort
  selector:
    app: gravity
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      nodePort: 30000
      name: listen
    - protocol: TCP
      port: 8222
      targetPort: 8222
      nodePort: 30001
      name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: gravity-nats-0
  namespace: ns-benchmark
spec:
  type: NodePort
  selector:
    app: gravity
    statefulset.kubernetes.io/pod-name: gravity-nats-0
  ports:
    - port: 7777
      targetPort: metrics
      nodePort: 30007  

---
apiVersion: v1
kind: Service
metadata:
  name: gravity-nats-1
  namespace: ns-benchmark
spec:
  type: NodePort
  selector:
    app: gravity
    statefulset.kubernetes.io/pod-name: gravity-nats-1
  ports:
    - port: 7777
      targetPort: metrics
      nodePort: 30008

---
apiVersion: v1
kind: Service
metadata:
  name: gravity-nats-2
  namespace: ns-benchmark
spec:
  type: NodePort
  selector:
    app: gravity
    statefulset.kubernetes.io/pod-name: gravity-nats-2
  ports:
    - port: 7777
      targetPort: metrics
      nodePort: 30009