apiVersion: v1
kind: Service
metadata:
  name: nats-external-service
  namespace: ns-benchmark
spec:
  type: NodePort
  selector:
    app: gravity
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      nodePort: 30000
      name: listen
    - protocol: TCP
      port: 8222
      targetPort: 8222
      nodePort: 30001
      name: monitor