# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv-nats-0
#   namespace: ns-benchmark
# spec:
#   capacity:
#     storage: 500Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   local:
#     path: /nfs-for-test/performance/kv_benchmark
#   persistentVolumeReclaimPolicy: Retain
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv-nats-1
#   namespace: ns-benchmark
# spec:
#   capacity:
#     storage: 500Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   local:
#     path: /nfs-for-test/performance/kv_benchmark
#   persistentVolumeReclaimPolicy: Retain
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv-nats-2
#   namespace: ns-benchmark
# spec:
#   capacity:
#     storage: 500Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   local:
#     path: /nfs-for-test/performance/kv_benchmark
#   persistentVolumeReclaimPolicy: Retain
